/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppFavoritesIndexRouteImport } from './pages/_app/favorites/index'
import { Route as AppHomeIndexRouteImport } from './pages/_app/_home/index'
import { Route as AppMovieMovieIdRouteImport } from './pages/_app/movie/$movieId'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFavoritesIndexRoute = AppFavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMovieMovieIdRoute = AppMovieMovieIdRouteImport.update({
  id: '/movie/$movieId',
  path: '/movie/$movieId',
  getParentRoute: () => AppLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/movie/$movieId': typeof AppMovieMovieIdRoute
  '/': typeof AppHomeIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
}
export interface FileRoutesByTo {
  '/movie/$movieId': typeof AppMovieMovieIdRoute
  '/': typeof AppHomeIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/_app/movie/$movieId': typeof AppMovieMovieIdRoute
  '/_app/_home/': typeof AppHomeIndexRoute
  '/_app/favorites/': typeof AppFavoritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/movie/$movieId' | '/' | '/favorites'
  fileRoutesByTo: FileRoutesByTo
  to: '/movie/$movieId' | '/' | '/favorites'
  id:
    | '__root__'
    | '/_app'
    | '/_app/movie/$movieId'
    | '/_app/_home/'
    | '/_app/favorites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/favorites/': {
      id: '/_app/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/_home/': {
      id: '/_app/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/movie/$movieId': {
      id: '/_app/movie/$movieId'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof AppMovieMovieIdRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppMovieMovieIdRoute: typeof AppMovieMovieIdRoute
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppFavoritesIndexRoute: typeof AppFavoritesIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppMovieMovieIdRoute: AppMovieMovieIdRoute,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppFavoritesIndexRoute: AppFavoritesIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
