/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppFavoritesIndexRouteImport } from './pages/_app/favorites/index'
import { Route as AppHomeIndexRouteImport } from './pages/_app/_home/index'

const AppFavoritesIndexRoute = AppFavoritesIndexRouteImport.update({
  id: '/_app/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/_app/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppHomeIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppHomeIndexRoute
  '/favorites': typeof AppFavoritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_home/': typeof AppHomeIndexRoute
  '/_app/favorites/': typeof AppFavoritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favorites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites'
  id: '__root__' | '/_app/_home/' | '/_app/favorites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppFavoritesIndexRoute: typeof AppFavoritesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/favorites/': {
      id: '/_app/favorites/'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AppFavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_home/': {
      id: '/_app/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppFavoritesIndexRoute: AppFavoritesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
